apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "login-management-system.fullname" . }}-config
  labels:
    {{- include "login-management-system.labels" . | nindent 4 }}
data:
  # Spring Profile
  SPRING_PROFILES_ACTIVE: "{{ .Values.environment }}"
  TZ: "Asia/Kolkata"

  # Database Configuration
  POSTGRES_URL: "jdbc:postgresql://{{ .Values.postgresql.fullname }}:{{ .Values.postgresql.primary.service.port }}/{{ .Values.postgresql.auth.database }}"
  POSTGRES_DATABASE: "{{ .Values.postgresql.auth.database }}"
  # Vault Secret Paths for PostgreSQL
  POSTGRES_SECRET_PATH: "{{ .Values.vault.secretPaths.postgres }}"

  # JWT Configuration
  JWT_TOKEN_VALIDITY: "{{ .Values.config.jwt.tokenValidity }}"
  JWT_SECRET_KEY: "{{ .Values.config.jwt.secretKey }}"

  # CORS Configuration
  CORS_ALLOWED_ORIGINS: "{{ .Values.config.cors.allowedOrigins }}"
  CORS_ALLOWED_METHODS: "{{ .Values.config.cors.allowedMethods }}"
  CORS_ALLOWED_HEADERS: "{{ .Values.config.cors.allowedHeaders }}"

  # JPA Configuration
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"

  # Security Configuration
  SPRING_SECURITY_USER_NAME: "admin"
  SPRING_SECURITY_USER_PASSWORD: "admin123"

  # Metrics Configuration
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  MANAGEMENT_METRICS_TAGS_APPLICATION: "login-management-system-{{ .Values.environment }}"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "{{ .Values.monitoring.prometheus.enabled }}"
